name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install psutil pyadl pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole system_monitor_overlay.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: system_monitor_overlay
          path: dist/system_monitor_overlay.exe
